MAPatients/MAPatients/Controllers/MAMedicationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MAPatients.Models;
using Microsoft.AspNetCore.Http;

namespace MAPatients.Controllers
{
    public class MAMedicationController : Controller
    {
        private readonly PatientsContext _context;

        public MAMedicationController(PatientsContext context)
        {
            _context = context;
        }

        // GET: MAMedication
        public async Task<IActionResult> Index(string id,string name)
        {
            if (String.IsNullOrWhiteSpace(id))
            {
                if (String.IsNullOrEmpty(HttpContext.Session.GetString("code")))
                {
                    TempData["Error"] = "No medication type code available";

                    return RedirectToAction("Index", "MAMedicationType");

                }
                else
                {
                    id = HttpContext.Session.GetString("code");
                }
            }
            else
            {
                HttpContext.Session.SetString("code", id);
            }
            if (String.IsNullOrWhiteSpace(name) || String.IsNullOrEmpty(name))
            {
                name = _context.MedicationType.FirstOrDefault(c => c.MedicationTypeId == Convert.ToInt32(id)).Name;
            }
            ViewData["Name"] = name;
            ViewData["medicationName"] = name;
            var patientsContext = _context.Medication
                .Include(m => m.ConcentrationCodeNavigation)
                .Include(m => m.DispensingCodeNavigation).Include(m => m.MedicationType)
                .Where(m => m.MedicationTypeId.ToString() == id) 
               .OrderBy(m=>m.Name).ThenBy(m=>m.Concentration) ;
            return View(await patientsContext.ToListAsync());
        }

        // GET: MAMedication/Details/5
        public async Task<IActionResult> Details(string id,string medicationName)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medication = await _context.Medication
                .Include(m => m.ConcentrationCodeNavigation)
                .Include(m => m.DispensingCodeNavigation)
                .Include(m => m.MedicationType)
                .FirstOrDefaultAsync(m => m.Din == id);
            if (medication == null)
            {
                return NotFound();
            }
            ViewData["medicationName"] = medicationName;
            return View(medication);
        }

        // GET: MAMedication/Create
        public IActionResult Create(string medicationName)
        {
            ViewData["ConcentrationCode"] = new SelectList(_context.ConcentrationUnit.OrderBy(m => m.ConcentrationCode), "ConcentrationCode", "ConcentrationCode");
            ViewData["DispensingCode"] = new SelectList(_context.DispensingUnit.OrderBy(m=>m.DispensingCode), "DispensingCode", "DispensingCode");
            ViewData["MedicationTypeId"] = new SelectList(_context.MedicationType, "MedicationTypeId", "Name");
            ViewData["medicationName"] = medicationName;
            return View();
        }

        // POST: MAMedication/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string medicationName,[Bind("Din,Name,Image,MedicationTypeId,DispensingCode,Concentration,ConcentrationCode")] Medication medication)
        {
            if (_context.Medication.Any(m => m.Name == medication.Name) && _context.Medication.Any(m => m.Concentration == medication.Concentration) && _context.Medication.Any(m => m.ConcentrationCode == medication.ConcentrationCode))
            {
                ModelState.AddModelError("Name", "Medication already exists");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(medication);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    return View("Error", new ErrorViewModel { ErrorMessage = " An error occured while saving the new entries.please, fill the empty fields" });
                }
            }
            ViewData["ConcentrationCode"] = new SelectList(_context.ConcentrationUnit.OrderBy(m => m.ConcentrationCode), "ConcentrationCode", "ConcentrationCode", medication.ConcentrationCode);
            ViewData["DispensingCode"] = new SelectList(_context.DispensingUnit.OrderBy(m => m.DispensingCode), "DispensingCode", "DispensingCode", medication.DispensingCode);
            ViewData["MedicationTypeId"] = new SelectList(_context.MedicationType, "MedicationTypeId", "Name", medication.MedicationTypeId);
            ViewData["medicationName"] = medicationName;

            return View(medication);
        }

        // GET: MAMedication/Edit/5
        public async Task<IActionResult> Edit(string id,string medicationName)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medication = await _context.Medication.FindAsync(id);
            if (medication == null)
            {
                return NotFound();
            }
            ViewData["ConcentrationCode"] = new SelectList(_context.ConcentrationUnit, "ConcentrationCode", "ConcentrationCode", medication.ConcentrationCode);
            ViewData["DispensingCode"] = new SelectList(_context.DispensingUnit, "DispensingCode", "DispensingCode", medication.DispensingCode);
            ViewData["MedicationTypeId"] = new SelectList(_context.MedicationType, "MedicationTypeId", "Name", medication.MedicationTypeId);
            ViewData["medicationName"] = medicationName;
            return View(medication);
        }

        // POST: MAMedication/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id,string medicationName, [Bind("Din,Name,Image,MedicationTypeId,DispensingCode,Concentration,ConcentrationCode")] Medication medication)
        {
            if (id != medication.Din)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(medication);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MedicationExists(medication.Din))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ConcentrationCode"] = new SelectList(_context.ConcentrationUnit, "ConcentrationCode", "ConcentrationCode", medication.ConcentrationCode);
            ViewData["DispensingCode"] = new SelectList(_context.DispensingUnit, "DispensingCode", "DispensingCode", medication.DispensingCode);
            ViewData["MedicationTypeId"] = new SelectList(_context.MedicationType, "MedicationTypeId", "Name", medication.MedicationTypeId);
            ViewData["medicationName"] = medicationName;
            return View(medication);
        }

        // GET: MAMedication/Delete/5
        public async Task<IActionResult> Delete(string id,string medicationName)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medication = await _context.Medication
                .Include(m => m.ConcentrationCodeNavigation)
                .Include(m => m.DispensingCodeNavigation)
                .Include(m => m.MedicationType)
                .FirstOrDefaultAsync(m => m.Din == id);
            if (medication == null)
            {
                return NotFound();
            }
            ViewData["medicationName"] = medicationName;

            return View(medication);
        }

        // POST: MAMedication/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            try
            {
                var medication = await _context.Medication.FindAsync(id);
                _context.Medication.Remove(medication);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            catch (Exception)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = " in order to delete the medication, you have to delete related any MedicationType using this Type" });
            }
        }
private bool MedicationExists(string id)
        {
            return _context.Medication.Any(e => e.Din == id);
        }
    }
}

MAPatients/MAPatients/Controllers/MAMedicationTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MAPatients.Models;

namespace MAPatients
{
    public class MAMedicationTypesController : Controller
    {
        private readonly PatientsContext _context;

        public MAMedicationTypesController(PatientsContext context)
        {
            _context = context;
        }

        // GET: MAMedicationTypes
        public async Task<IActionResult> Index()
        {
            return View(await _context.MedicationType.OrderBy(m=>m.Name).ToListAsync());
        }

        //list records MAMedicationTypes
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medicationType = await _context.MedicationType
                .FirstOrDefaultAsync(m => m.MedicationTypeId == id);
            if (medicationType == null)
            {
                return NotFound();
            }

            return View(medicationType);
        }

        // Create new MAMedicationTypes
        public IActionResult Create()
        {
            return View();
        }

        //create records
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name")] MedicationType medicationType)
        {
            if (ModelState.IsValid)
            {
                _context.Add(medicationType);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(medicationType);
        }

        // GET: MAMedicationTypes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medicationType = await _context.MedicationType.FindAsync(id);
            if (medicationType == null)
            {
                return NotFound();
            }
            return View(medicationType);
        }

        // edit records
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MedicationTypeId,Name")] MedicationType medicationType)
        {
            if (id != medicationType.MedicationTypeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(medicationType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MedicationTypeExists(medicationType.MedicationTypeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(medicationType);
        }

        // delete records for madication type
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medicationType = await _context.MedicationType
                .FirstOrDefaultAsync(m => m.MedicationTypeId == id);
            if (medicationType == null)
            {
                return NotFound();
            }

            return View(medicationType);
        }

        // delete records MAMedicationTypes
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            // using (try catch) to handle the delete of forign key records.
            try
            {
                var medicationType = await _context.MedicationType.FindAsync(id);
                _context.MedicationType.Remove(medicationType);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = " in order to delete the MedicationTypeId  , you have to delete related Medication using this Type" });
            }
        }

        private bool MedicationTypeExists(int id)
        {
            return _context.MedicationType.Any(e => e.MedicationTypeId == id);
        }
    }
}

MAPatients/MAPatients/Views/MAMedicationTypes/Create.cshtml
@model MAPatients.Models.MedicationType

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>MedicationType</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MAPatients/MAPatients/Views/MAMedicationTypes/Delete.cshtml
@model MAPatients.Models.MedicationType

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MedicationType</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MedicationTypeId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MedicationTypeId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MedicationTypeId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MAPatients/MAPatients/Views/MAMedicationTypes/Details.cshtml
@model MAPatients.Models.MedicationType

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>MedicationType</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MedicationTypeId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MedicationTypeId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.MedicationTypeId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MAPatients/MAPatients/Views/MAMedicationTypes/Edit.cshtml
@model MAPatients.Models.MedicationType

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>MedicationType</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MedicationTypeId" class="control-label"></label>
                <input  asp-for="MedicationTypeId" class="form-control" readonly/>
                <span asp-validation-for="MedicationTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MAPatients/MAPatients/Views/MAMedicationTypes/Index.cshtml
@model IEnumerable<MAPatients.Models.MedicationType>

@{
    ViewData["Title"] = "Medication Type";
}

<h1>List OF Medication Type</h1>
<h3 class="text-danger">@TempData["Error"]</h3>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MedicationTypeId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MedicationTypeId)
            </td>
            <td>
                <a asp-controller="MAMedication" asp-action="Index" asp-route-id="@item.MedicationTypeId" 
                   asp-route-name="@item.Name">
                @Html.DisplayFor(modelItem => item.Name)</a>
               
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.MedicationTypeId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.MedicationTypeId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.MedicationTypeId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>